# Generated by Django 5.1.6 on 2025-02-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='order',
        ),
    ]
